<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WebMenu_userIcon</name>
   <tag></tag>
   <elementGuidId>bc2cfb98-30e7-41b1-a32d-4481e7135685</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>md-icon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[1]/abb-header[2]/header[@class=&quot;row ng-scope&quot;]/nav[@id=&quot;mainNav&quot;]/ul[@class=&quot;u-pull-right&quot;]/li[2]/a[1]/md-icon[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>md-svg-src</name>
      <type>Main</type>
      <value>data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCI+PHRpdGxlPkNvbW1vblVYX1VzZXJfMjQ8L3RpdGxlPjxwYXRoIGQ9Ik0yMCwxNi41VjIySDRWMTYuNUM0LDE0LDcuNTcsMTIsMTIsMTJTMjAsMTQsMjAsMTYuNVpNMTIsMmE0LDQsMCwxLDAsNCw0QTQsNCwwLDAsMCwxMiwyWiIgZmlsbD0iI2ZmZiIvPjwvc3ZnPg==</value>
   </webElementProperties>
</WebElementEntity>
