<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>05b2_Control</name>
   <tag></tag>
   <elementGuidId>9072791a-0cc8-40c3-b23d-91f7b0b6d922</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt-center</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[1]/div[@class=&quot;u-full-width headerPadding ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/ng-include[@class=&quot;frame_content ng-scope&quot;]/div[@class=&quot;twelve columns ng-scope&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;mainContent nine columns no-margin&quot;]/table[@class=&quot;zebra ng-scope&quot;]/thead[1]/tr[1]/th[@class=&quot;txt-center&quot;]</value>
   </webElementProperties>
</WebElementEntity>
