<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>02_ID</name>
   <tag></tag>
   <elementGuidId>f6d17251-6cea-4855-beac-c1a923b85bfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//DIV[count(. | /html/body/div[1]/div/ng-include/div/div/div[2]/table/thead/tr/th[1]/column-sortable/div) = count(/html/body/div[1]/div/ng-include/div/div/div[2]/table/thead/tr/th[1]/column-sortable/div)]</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/ng-include/div/div/div[2]/table/thead/tr/th[1]/column-sortable/div</value>
   </webElementProperties>
</WebElementEntity>
