<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>04_ReferencePartNumber</name>
   <tag></tag>
   <elementGuidId>b3aeec9f-b60b-44f9-aa53-c28b7bbe03ea</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/ng-include/div/div/div[2]/table/thead/tr/th[3]/column-sortable/div</value>
   </webElementProperties>
</WebElementEntity>
