<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>01_li_Assets</name>
   <tag></tag>
   <elementGuidId>dc31979c-c3d5-4f20-abd8-9a10738b07df</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[1]/div[@class=&quot;u-full-width headerPadding ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/ng-include[@class=&quot;frame_content ng-scope&quot;]/div[@class=&quot;twelve columns ng-scope&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;sidebar-container three columns ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/nav[1]/ul[1]/li[@class=&quot;title&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Assets</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title</value>
   </webElementProperties>
</WebElementEntity>
