<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_REACT-3.6(4.6)-TL</name>
   <tag></tag>
   <elementGuidId>03ad618e-33e1-4954-988c-1ec44674dd1d</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#!/product-families/datasheet/REACT-3.6(4.6)-TL</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>REACT-3.6(4.6)-TL</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[1]/div[@class=&quot;u-full-width headerPadding ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/ng-include[@class=&quot;frame_content ng-scope&quot;]/div[@class=&quot;twelve columns ng-scope&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;mainContent nine columns no-margin&quot;]/table[@class=&quot;zebra&quot;]/tbody[1]/tr[@class=&quot;ng-scope&quot;]/td[2]/a[@class=&quot;ng-binding&quot;]</value>
   </webElementProperties>
</WebElementEntity>
